version: '3.6'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
      - angular
    environment:
      - DISPLAY=:99
    entrypoint: /bin/sh -c "Xvfb :99 -screen 0 1280x1024x24 & ./node_modules/.bin/cypress run --config-file cypress.config.js"
