# Use the Cypress included image with all dependencies
FROM cypress/included:13.13.1

# Set working directory
WORKDIR /usr/src/app

# Copy Cypress configuration and tests
COPY cypress /usr/src/app/cypress
COPY cypress.config.js /usr/src/app/cypress.config.js

# Confirm the Cypress installation
RUN npx cypress verify

# Start the Cypress tests directly
ENTRYPOINT ["npx", "cypress", "run", "--config-file", "cypress.config.js"]
