version: '3.6'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
      angular:
        condition: service_healthy
    environment:
      - DISPLAY=:99
    entrypoint: /bin/sh -c "Xvfb :99 -screen 0 1280x1024x24 & ./node_modules/.bin/cypress run --config-file cypress.config.js"
