version: '3.6'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - '4200:4200'
  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
      - angular
    network_mode: 'host'
