version: '3.6'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8084:80'
  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    depends_on:
      - angular
    network_mode: 'host'
